### PR TITLE
Simplify release process

### PR DESCRIPTION
**Pull request by laughedelic**
After #35 some things in the release will be broken. But with the new version plugin things can be simplified a lot: 
- no `version.sbt`, no writing to files and committing it during release
- to start release process you choose: `major`, `minor`, `bugfix`, `milestone`, or `releaseCandidate` and the version is set automatically (and no need in the "next" version, as now we have only current version)

---

Here is a draft of the simplified release process:
1. pre-release checks (before any changes are introduced). if any of these checks don't pass, there's no point in even starting the release process.
   - [x] `checkGit`:
     - no uncommited changes
     - check that there's no tag with the release version name already
     - update remote and check that current branch is up to date (being ahead is ok)
     - check GitHub credentials
   - [x] `checkCodeNotes`: TODO/FIXME list (ask to continue if there are some)
   - [x] `checkDependencies`: 
     - no snapshot dependencies
     - check dependency updates (ask to continue if there are some)
     - run `update`
   - [x] run _non-release_ tests (`test in Test`)
   - [x] `prepareReleaseNotesAndTag`:
     - check release notes for corresponding version (show and confirm)
     - rename them and commit if needed
     - create git tag for the release version
2. **reload**. after this `version` setting has the release version used by all further steps.
3. package and publish artifacts
4. run release-only tests (they may require the artifact)
5. publish GitHub release:
   - push git tag
   - run `releaseOnGithub`
6. handle external documentation (should be optional):
   - clean/generate literator source docs, commit and push it
   - generate API docs and push them to GitHub-pages

---

If steps 3 or 4 fail, we can always checkout the newly made tag and delete it (so the release process is aborted without any changes introduced). After step 5 the tag became public and any changes should go in the next release.

### CODE REVIEW

**Comment by eparejatobes** [comment]
Good!

One note about this: shouldn't we publish test before running them, in case the tests require an artifact?

**Comment by laughedelic** [comment]
Right, but then it should be a release-only test. So I would run non-release tests only in pre-release checks, then publish and after then run release-only tests.
This also means that if some of them fail we have to roll-back changes and "unpublish" the artifact.

**Comment by eparejatobes** [comment]
@laughedelic is this already kinda usable?

**Comment by laughedelic** [comment]
Not yet, sorry. The pre-release checks part is done, but the rest is not yet, so you can't make an actual release with it. I'll finish it today or tomorrow.

**Comment by laughedelic** [comment]
@eparejatobes see https://github.com/ohnosequences/cosas/pull/119.
You can start using `0.7.0-104-g945daa8` now. I will publish a RC with working release process this weekend.

**Comment by laughedelic** [comment]
I have released 0.8.0-RC1 to try the plugin on itself. The main part works fine. The docs part is a bit buggy:
- literator docs should be commited immediately after generation
- new API docs should be added to git before commiting them (I thought that explicitly listing files in `git commit` adds them, but it works only for known files)

**Comment by laughedelic** [comment]
Issues identified while working on https://github.com/ohnosequences/db.rnacentral/issues/16:

- [ ] StatikaBundleSettings: object name should be transformed to avoid dots and dashes
- [ ] BuildInfoPlugin somehow interferes with the ReleasePlugin's `generateTestTags`. Adding this to the build helps:

  ```scala
  sourceGenerators in Test += ohnosequences.sbt.nice.Release.generateTestTags.taskValue
  ```
  
  but it has to be solved in the plugin.

**Comment by laughedelic** [comment]
About the first one: https://github.com/sbt/sbt/issues/2696

**Comment by laughedelic** [comment]
TODO:
- [ ] add publish to the `ReleaseTest` config and add it in the release process before `test in ReleaseTest`

**Comment by laughedelic** [comment]
See also https://github.com/ohnosequences/db.rna16s/issues/46#issuecomment-238832130 for the general overview of the fat-jar publishing issue.

**Comment by laughedelic** [comment]
@eparejatobes now that I think about it, we don't use published fat-jar as sbt/ivy dependency so we don't need to publish/resolve it in any special way, why not just upload it to S3?

At the moment `AssemblySettings` provides `fatArtifactUrl` setting which constructs url based on the ivy/maven publishing patterns, so I can just add a _simple task which will upload the assembled jar to this url_. No need to interact with complicated sbt artifacts/publishing scoping system 👍

**Comment by eparejatobes** [comment]
jolly good! I'm just a bit uneasy about dependencies: are you sure we never had to depend on good ol' fatty jar?

**Comment by laughedelic** [comment]
It was like in Statika 1.0, when we were using sbt to run bundles code on EC2. Now we just download jar from a given S3 URL and run code with it.

**Comment by eparejatobes** [comment]
OK, fine then! #51 FTW

**Comment by laughedelic** [comment]
Finally solved! To add test sources to the fat-jar:

```scala
fullClasspath in assembly := (fullClasspath in Test).value 
```

**Comment by laughedelic** [comment]
Some notes about changes:

- `AssemblySettings` plugin provides `fatArtifactUpload` task, which runs `assembly` and just uploads the jar

- `assembly` task from the sbt-assembly plugin doesn't include test sources in the generated jar (which is logical). So if your tests depend on the published artifact, you need first to alter `assembly:fullClasspath` setting:

  ```scala
  fullClasspath in assembly := (fullClasspath in Test).value
  ```

- then `ReleasePlugin` has a boolean _setting_ `publishFatArtifact` (by analogy with the standard `publishArtifact`) and redefines `publish` in its scope. So if you want to publish fat-jar in release, just add

  ```scala
  publishFatArtifact in Release := true
  ```

**Comment by laughedelic** [comment]
Version `0.8.0-RC1-30-g8a6ab4c` can be treated as RC2 (which I will release later today).

**Comment by laughedelic** [comment]
Finally, released [RC2](https://github.com/ohnosequences/nice-sbt-settings/releases/tag/v0.8.0-RC2) which can be used for complete release process 🚢 
I'll try it on a couple more projects, if everything is fine, merge this branch and release 0.8.0.

---

Known issues:
- if you run `publishApiDocs` twice on the same revision it will fail second time because there are no changes (should improve the error message)

**Comment by laughedelic** [comment]
Version `0.8.0-RC2-4-g32959a3` with the mentioned improvements is published 🚀

**Comment by laughedelic** [comment]
Firther improvements:
- [ ] move `assembly` before artifacts publishing so that if it fails, no articats are published at all
- [ ] set github-release `org`/`repo` from remote url (see https://github.com/ohnosequences/sbt-github-release/issues/2 and https://github.com/ohnosequences/sbt-github-release/issues/6)

**Comment by laughedelic** [comment]
Mentioned improvements are release as [0.8.0-RC3](https://github.com/ohnosequences/nice-sbt-settings/releases/tag/v0.8.0-RC3). I'll test it in a couple of places and release as 0.8.0.

**Comment by eparejatobes** [comment]
see #54

**Comment by laughedelic** [comment]
@eparejatobes 
I just released [RC4](https://github.com/ohnosequences/nice-sbt-settings/releases/tag/v0.8.0-RC4) with #54 and another little fix. Try it, if it works fine, I will release final 0.8.0. Other mentioned improvements will go to the next release.

**Comment by laughedelic** [comment]
@eparejatobes @marina-manrique 
I just released [RC5](https://github.com/ohnosequences/nice-sbt-settings/releases/tag/v0.8.0-RC5) with the #57 bugfix and some version updates.

**Comment by eparejatobes** [comment]
Can we merge this uber-PR sometime soon?

**Comment by laughedelic** [comment]
Sure. I just wanted to update to Scala 2.12 and make the final release here.

**Comment by laughedelic** [comment]
Some more known issues here: 
- version warning is reported too many times on a fresh repo without any tags
- test-only tag name is broken for org names like `ohnosequences-bundles`, should replace dashes or something..

**Comment by laughedelic** [comment]
This pull-request lived too long... Goodbye 👋

**Pull request merged**
