### PR TITLE
Setting next version

### PR DESCRIPTION
**Pull request by laughedelic**
If you set version to `2.0.0-M1`, then the next version will be based on `2.0.0`: `2.1.0-SNAPSHOT`.

- it should be based on the current release version that you just set
- ideally, if you fix a particular policy of release versions, there shouldn't be such a question: next version should be set automatically, based on the release version

### CODE REVIEW

**Comment by laughedelic** [comment]
This is mostly done:
- `gitVersion` setting is added, it returns a structured version (see `Version.scala` source) based on `git describe` (only release-related tags, with "dirty" state `-SNAPSHOT` suffix)
- `version` setting uses `gitVersion` converted to a plain string. Example: `0.7.0-45-g6543b22`

And there are some limitations:
- `version` is not updated dynamically, you need to `reload` to catch up git-related changes (commits and dirty state) since sbt was previously loaded. See https://github.com/sbt/sbt-git/issues/31.
- I couldn't override `publish` task so far (will ask in sbt/sbt), but I disabled snapshots publishing through setting `publishTo` to `None` for snapshots. Again, this is a setting so it's loaded once per sbt load, so it may be not up to date. But on the other hand you should generally reload before you publish.
- I'm going to check the release process in a new issue and simplify it with the new version setting

**Comment by eparejatobes** [comment]
Is it possible to do something like this? https://github.com/sbt/sbt-git/issues/31#issuecomment-32376755

**Comment by laughedelic** [comment]
This was the plan for the release command, but for publishing I thought that if I define a command with the same name as the task they will conflict somehow. I tried now and actually it works. I'm going to push it tomorrow 👍

**Comment by laughedelic** [comment]
Done. So now there is a `publish` _command_, that first reloads and then runs another command which first checks whether the (updated) version is a snapshot (then stops and warns you), or if not, runs the `publish` _task_.

I'm going to merge this and rework the release process in another PR, but if you want to use this in development, you can refer to the published (using all this) `0.7.0-49-gc63ee34` version.

**Pull request merged**
